dbt_bigquery:
  outputs:
    dev:
      dataset: dbt_spersis
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/persis/Downloads/my-project-persis-1eb87ae4676d.json
      location: US
      method: service-account
      priority: interactive
      project: my-project-persis
      threads: 1
      type: bigquery
  target: dev

